export const ActionTypes = {
    SINGLE_POST: 'SINGLE_POST',
    SINGLE_POST_PENDING: 'SINGLE_POST_PENDING',
    SINGLE_POST_FULFILLED: 'SINGLE_POST_FULFILLED',

    GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
    GET_ALL_CATEGORIES_PENDING: 'GET_ALL_CATEGORIES_PENDING',
    GET_ALL_CATEGORIES_FULFILLED: 'GET_ALL_CATEGORIES_FULFILLED',

}